// VBConversions Note: VB project level imports
using System.Collections.Generic;
using System;
using System.Linq;
using System.Drawing;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Data;
using System.Xml.Linq;
using Microsoft.VisualBasic;
using System.Collections;
using System.Windows.Forms;
// End of VB project level imports

using BoTech;

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



namespace BoTech
{
	namespace My
	{
		
		//注意: 此文件是自动生成的；请不要直接修改它。若要进行更改，
		// 或者如果您在此文件中遇到生成错误，请转至项目设计器
		// (转至“项目属性”或在解决方案资源管理器中双击“我的项目”节点)，
		// 然后在“应用程序”选项卡中进行更改。
		//
		public partial class MyApplication : global::Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase
		{
			[STAThread]
			static void Main()
			{
				//添加异常捕获
				Application.ThreadException += new System.Threading.ThreadExceptionEventHandler(UIThreadException);
				Application.SetUnhandledExceptionMode(UnhandledExceptionMode.CatchException);
				AppDomain.CurrentDomain.UnhandledException += new UnhandledExceptionEventHandler(CurrentDomain_UnhandleException);

				(new MyApplication()).Run(new string[] {});
			}
			
			[global::System.Diagnostics.DebuggerStepThrough()]public MyApplication() : base(global::Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
			{
				this.IsSingleInstance = true;
				this.EnableVisualStyles = true;
				this.SaveMySettingsOnExit = true;
				this.ShutdownStyle = global::Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses;
			}
			
			[global::System.Diagnostics.DebuggerStepThroughAttribute()]protected override void OnCreateMainForm()
			{
				this.MainForm = global::BoTech.Frm_ICT_Main.Instance;
			}

			/// <summary>
			/// Windows窗体线程异常捕获处理，弹窗+本地Log保存
			/// </summary>
			private static void UIThreadException(object sender, System.Threading.ThreadExceptionEventArgs t)
			{
				try
				{
					string errMsg = "Windows窗体线程异常：\n\n";
					string msg = errMsg + t.Exception.Message + Environment.NewLine + t.Exception.StackTrace;
					//Common.WritePDCALog("程序异常捕获Log", msg);
					mGlobal._Logs.AddLog(GlobalUserInfoGet.GetLoginString, msg, LogsHelper.LogsType._other, 0, false);
					MessageBox.Show(msg);

				}
				catch (Exception)
				{
					string msg = "不可恢复的Windows窗体线程异常,应用程序即将退出！";
					//Common.WritePDCALog("程序异常捕获Log", msg);
					mGlobal._Logs.AddLog(GlobalUserInfoGet.GetLoginString, msg, LogsHelper.LogsType._other, 0, false);
					MessageBox.Show(msg);

				}
			}
			/// <summary>
			/// 非Windows窗体线程异常捕获处理，弹窗+本地Log保存
			/// </summary>
			private static void CurrentDomain_UnhandleException(object sender, UnhandledExceptionEventArgs e)
			{
				try
				{
					Exception ex = (Exception)e.ExceptionObject;
					string errMsg = "非Windows窗体线程异常：\n\n";
					string msg = errMsg + ex.Message + Environment.NewLine + ex.StackTrace;
					//Common.WritePDCALog("程序异常捕获Log", msg);
					mGlobal._Logs.AddLog(GlobalUserInfoGet.GetLoginString, msg, LogsHelper.LogsType._other, 0, false);
					MessageBox.Show(msg);

				}
				catch (Exception)
				{
					string msg = "不可恢复的非Windows窗体线程异常,应用程序即将退出！";
					//Common.WritePDCALog("程序异常捕获Log", msg);
					mGlobal._Logs.AddLog(GlobalUserInfoGet.GetLoginString, msg, LogsHelper.LogsType._other, 0, false);
					MessageBox.Show(msg);

				}
			}
		}
	}
	
}
